name: Famed Scanners

on: push

jobs:
  send_contracts_to_slither:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - run: |
          shopt -s globstar; tar -cvf archive.tar **/*.sol
          curl -X POST https://famed-github-backend-jeka2.ondigitalocean.app/famed/repos/elainemarais/Name/scanner -F "name=slither" -F files=@archive.tar
  send_contracts_to_semgrep:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - run: |
          shopt -s globstar; tar --exclude='./.git' -cvf archive.tar ./
          curl -X POST https://famed-github-backend-jeka2.ondigitalocean.app/famed/repos/elainemarais/Name/scanner -F "name=semgrep" -F files=@archive.tar
